#!/usr/bin/env bash
#
# インストール方法
# - Session Manager Plugin on Windows: CLIからSSMでログインするために必要
# - fzf: ログイン先候補の選択に利用
#
# Session Manager Plugin on Windowsインストール方法は下記
# <https://docs.aws.amazon.com/ja_jp/systems-manager/latest/userguide/session-manager-working-with-install-plugin.html>
# 
# fzfインストール方法は下記
# <https://github.com/junegunn/fzf#installation>
# - Linuxの場合下記がかんたん
# $ git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
# $ ~/.fzf/install
#
# 実行方法
# 環境変数AWS_PROFILEでprofileを指定後、
# $ ssm-session
# $ ssm-session eu-central-1
# 接続先リージョンは引数で指定。
#

set -o pipefail

REGION=""
if [ $# -eq 1 ];then
    REGION="--region $1"
fi

# Ignore SIGINT(Ctrl-C)
trap '' 2
aws ec2 describe-instances --filter "Name=instance-state-name,Values=running" ${REGION} \
    | jq -r '.Reservations[].Instances[] | {InstanceName: (.Tags[] | select(.Key=="Name").Value), InstanceId} | [.InstanceName, .InstanceId] | @tsv' \
    | fzf \
    | cut -f 2 \
    | xargs  -o aws ssm start-session ${REGION} --target
