name: UbuntuCI

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install required base packege
        run: apt-get update && apt-get install -y git sudo curl unzip
      - name: Install dotfiles
        run: ./install.sh
