name: CI

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install required base packege
        run: apt-get update && apt-get install -y git sudo curl unzip tzdata
      - name: Install init packeges
        run: ./install/init.sh
      - name: Install dotfiles
        run: ./install/install.sh install
      - name: Test command
        run: aws --version && node -v
